version: '3.8'
services:
  php:
    build: .
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./:/var/www/html
    depends_on:
    - db
  db:
    container_name: db
    image: mysql:5.7
    volumes:
    - /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gameEinstein
        MYSQL_USER: gameEinstein
        MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db